[package]
name = "webability-rust"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Cliente oficial en Rust para la API pública de WebAbility (https://api.webability.info)."
homepage = "https://github.com/webability/webability-rust"
repository = "https://github.com/webability/webability-rust"
authors = ["Philippe Thomassigny"]
keywords = ["webability", "api", "dns", "mail"]

[dependencies]
